### ISSUE TITLE
Erro qb-radialmenu

### ISSUE THREAD

**Issue by Duruteu** [MaDHouSe79/mh-drivingteacherjob#1]
Hello friend I'm loving your script I just have a problem this code is appearing.

[script:qb-radialmenu] Error parsing script @qb-radialmenu/config.lua in resource qb-radialmenu: @qb-radialmenu/config.lua:730: '}' expected (to close '{' at line 480) near '['

Can you tell me how to solve?

**Comment by MaDHouSe79** [comment]
can i see you config file from you qb-radialmenu?

i think you mis a `}` at the end of the `Config.JobInteractions`

**Comment by Duruteu** [comment]
It was a mistake my friend I copied the codes but I didn't change the lines so it wasn't working, thanks for helping me I really like your scripts. ;)
