### ISSUE TITLE
Problem in script

### ISSUE THREAD

**Issue by zerlot120** [MaDHouSe79/mh-drivingteacherjob#2]
Hi mate!

when I first run the script i get error
https://media.discordapp.net/attachments/990367332016726046/1076930580995915887/image.png

but when I restart the script, everything works while I'm connected to the game, after I make a relog, the same problem comes back.

do you have any suggestion where the error occurs?

**Comment by MaDHouSe79** [comment]
i just change it, check if you have this in fxmanifest.lua

```lua
client_scripts {
    '@PolyZone/client.lua',
    '@PolyZone/BoxZone.lua',
    '@PolyZone/EntityZone.lua',
    '@PolyZone/CircleZone.lua',
    '@PolyZone/ComboZone.lua',
    'client/main.lua',
}
````

**Comment by zerlot120** [comment]
in my side  

client_scripts {
    '@PolyZone/client.lua',
	'@PolyZone/BoxZone.lua',
	'@PolyZone/ComboZone.lua',
    'client/main.lua',
}

**Comment by zerlot120** [comment]
I moved the stream folder to another location so that I can restart the script. I put what you put as a solution but I still have the same error

**Comment by MaDHouSe79** [comment]
It looks like you don't have the dependencie `Polyzone`. you need this to make it work.
cause i just install it on a new server and it works just fine here
