### ISSUE TITLE
Hello, is it possible to solve this?

### ISSUE THREAD

**Issue by Drazendrazan** [MaDHouSe79/mh-drivingteacherjob#3]
[resources:mh-driving] Warning: could not find file `data/**/*.xml` (defined in fxmanifest.lua:33)
[resources:mh-driving] Warning: could not find file `data/**/*.dat` (defined in fxmanifest.lua:33)
[resources:mh-driving] Warning: could not find file `data/**/*.ytyp` (defined in fxmanifest.lua:33)
[resources:mh-driving] Warning: could not find file `data/**/*.cs` (defined in fxmanifest.lua:33)

**Comment by MaDHouSe79** [comment]
change it to this, or look in the file here in githud:

files {
    'data/*.meta', 
    'data/*.xml',
    'data/*.dat',
    'data/*.ytyp',    
    'data/*.cs',
}

data_file 'HANDLING_FILE'            'data/handling*.meta'
data_file 'VEHICLE_LAYOUTS_FILE'    'data/vehiclelayouts*.meta'
data_file 'VEHICLE_METADATA_FILE'    'data/vehicles*.meta'
data_file 'CARCOLS_FILE'            'data/carcols*.meta'
data_file 'VEHICLE_VARIATION_FILE'    'data/carvariations*.meta'
data_file 'CONTENT_UNLOCKING_META_FILE' 'data/unlocks.meta'
data_file 'PTFXASSETINFO_FILE' 'data/ptfxassetinfo.meta'
