### ISSUE TITLE
No spawn car in qb-radialmenu

### ISSUE THREAD

**Issue by Aliilouuw** [MaDHouSe79/mh-drivingteacherjob#4]
hello, I have a problem with qb-radialmenu. I don't have a spawn car toggle. please help me.

**Comment by MaDHouSe79** [comment]
use the garages on the map, you have a garage with your drivingschool. you need to go there. 

The F1 menu for vehicle spawn is not in the script anymore.

**Comment by Aliilouuw** [comment]
thank you for your quick return. that explains everything. but even the car school garage does not work. a big thank you to you.

I have an error message isPointIn what is it?

**Comment by Aliilouuw** [comment]
thank you for your quick return. that explains everything. but even the car school garage does not work. a big thank you to you.

I have an error message isPointIn what is it?

**Comment by MaDHouSe79** [comment]
you need to load the script after polyzone and target, cause it needs some functions from scripts, 
so ensure it after the `ensure [standalone]`.
