### ISSUE TITLE
Error in script mh-drivingteacherjob/client/main.lua

### ISSUE THREAD

**Issue by zerlot120** [MaDHouSe79/mh-drivingteacherjob#5]
On new instaled qb-core default server today .
I set everything up as in the manual, but there is a problem with creating the garage.

CreateThread(function()
    while true do
        if LocalPlayer.state.isLoggedIn then
            local ped = PlayerPedId()
            local pos = GetEntityCoords(ped)
            local isPointInside = garageCombo:isPointInside(pos)
            if QBCore.Functions.GetPlayerData().job.name == 'drivingteacher' and QBCore.Functions.GetPlayerData().job.onduty then
                if isPointInside then
                    if IsPedInAnyVehicle(ped, false) then
                        exports['qb-core']:DrawText(Lang:t('menu.park_vehicle'))
                    else
                        exports['qb-core']:DrawText(Lang:t('menu.open_garage'))
                    end
                    isInside = true
                else
                    if isInside then exports['qb-core']:HideText() end
                    isInside = false
                end
            end
        end
        Wait(1000)
    end
end)

![image](https://github.com/MaDHouSe79/mh-drivingteacherjob/assets/30410607/7404a63b-22ac-4d92-bde4-c3ab26615851)

it seems like it has a problem when creating garages

newly installed qb-core server only with that script. I get that error, have you encountered such an error?

my server is on linux

**Comment by MaDHouSe79** [comment]
you need to load it after the `ensure [standalone]` folder.

**Comment by zerlot120** [comment]
![image](https://github.com/MaDHouSe79/mh-drivingteacherjob/assets/30410607/8a9abcf8-48df-4029-b1ac-3d136709c246)

it is after

**Comment by zerlot120** [comment]
the script works, but the part from the garage doesn't work for me

**Comment by MaDHouSe79** [comment]
download it again i think i fix it.

**Comment by zerlot120** [comment]
I added to the translation
[mh]/mh-drivingteacherjob/locales/en.lua
 ['select_vehicle'] = "Odaberite Vozilo",


i woks now 
![image](https://github.com/MaDHouSe79/mh-drivingteacherjob/assets/30410607/b6966632-d834-4d67-abbd-5c106986c1f5)

but it still gives me error, and when you go to the  garage vehicle selection, you have to press e a few times to open the interface

**Comment by MaDHouSe79** [comment]
just don't spam the E button, it take 1 sec before the menu open.

Edit: i just update the code again, hope the error is now gone.

Edit2 if you want it faster the press [E] you need to go to https://github.com/MaDHouSe79/mh-drivingteacherjob/blob/51d6d18f0fcfb60c81273685e86715406d3ce873/client/main.lua#L701 and change the 1000 to 10.

**Comment by zerlot120** [comment]
it works, thank you very much

**Comment by zerlot120** [comment]
it works, thank you very much

**Comment by zerlot120** [comment]
it works, thank you very much
